

o:
	g++ -c hhmm.cc
	g++ -c LeapYear.cc
	g++ -c DateSplit.cc
	g++ -c DateJoin.cc
	g++ -c DayNo.cc
	g++ -c PlusDay.cc
	g++ -c MinusDay.cc
	g++ -c DateDifference.cc
	g++ -c TimeDifference.cc
	g++ -c MidTime.cc
