name: "Monthly Test"

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight UTC on the 1st of every month

run-name: Monthly Package and Test DateTimeTools
jobs:
  package_and_test:
    uses: ./.github/workflows/package_test.yml
    with:
        python_version: "3.14"
        linux: true
        windows-msvc: true
        macos: true
        source: false
