name: "Package Test"

on: 
    pull_request:
    workflow_dispatch:
        inputs:
            python_version:
                type: choice
                description: "Python version to run package test on"
                default: "3.14"
                options:
                    - "all"
                    - "3.10"
                    - "3.11"
                    - "3.12"
                    - "3.13"
                    - "3.14"
            linux:
                type: boolean
                description: "Build Linux package (x86_64)"
                default: true
            linux-arm:
                type: boolean
                description: "Build Linux package (aarch64)"
                default: true
            windows:
                type: boolean
                description: "Build Windows package (x86_64, MSYS2)"
                default: false
            windows-arm:
                type: boolean
                description: "Build Windows package (aarch64, MSYS2)"
                default: false
            windows-msvc:
                type: boolean
                description: "Build Windows package (x86_64, MSVC)"
                default: false
            windows-msvc-arm:
                type: boolean
                description: "Build Windows package (aarch64, MSVC)"
                default: false
            macos:
                type: boolean
                description: "Build macOS package (x86_64)"
                default: false
            macos-arm:
                type: boolean
                description: "Build macOS package (aarch64)"
                default: false
            source:
                type: boolean
                description: "Build Source package"
                default: false
    workflow_call:
        inputs:
            python_version:
                type: string
                description: "Python version to run package test on"
                default: "3.14"
            linux:
                type: boolean
                description: "Build Linux package (x86_64)"
                default: true
            linux-arm:
                type: boolean
                description: "Build Linux package (aarch64)"
                default: true
            windows:
                type: boolean
                description: "Build Windows package (x86_64, MSYS2)"
                default: false
            windows-arm:
                type: boolean
                description: "Build Windows package (aarch64, MSYS2)"
                default: false
            windows-msvc:
                type: boolean
                description: "Build Windows package (x86_64, MSVC)"
                default: false
            windows-msvc-arm:
                type: boolean
                description: "Build Windows package (aarch64, MSVC)"
                default: false
            macos:
                type: boolean
                description: "Build macOS package (x86_64)"
                default: false
            macos-arm:
                type: boolean
                description: "Build macOS package (aarch64)"
                default: false
            source:
                type: boolean
                description: "Build Source package"
                default: false

run-name: Package and Test DateTimeTools
jobs:
    setup_inputs:
        name: Setup Jobs
        runs-on: ubuntu-latest
        steps:
            - name: Set up job matrix
              id: setup_matrix
              run: |
                python3 .github/scripts/setup_package_test_matrix.py \
                  --python-version "${{ github.event.inputs.python_version }}" \
                  --linux "${{ github.event.inputs.linux }}" \
                  --linux-arm "${{ github.event.inputs.linux-arm }}" \
                  --windows "${{ github.event.inputs.windows }}" \
                  --windows-arm "${{ github.event.inputs.windows-arm }}" \
                  --windows-msvc "${{ github.event.inputs.windows-msvc }}" \
                  --windows-msvc-arm "${{ github.event.inputs.windows-msvc-arm }}" \
                  --macos "${{ github.event.inputs.macos }}" \
                  --macos-arm "${{ github.event.inputs.macos-arm }}" \
                  --source "${{ github.event.inputs.source }}"
                


    build_linux:
      needs: setup_inputs
      if: ${{ needs.setup_inputs.outputs.matrix-linux == 'true' }}
      uses: ./.github/workflows/build_linux.yml
      strategy:
          matrix:
              python_version: ["3.10","3.11","3.12","3.13","3.14"]
              arch: ["x86_64", "aarch64"]
          fail-fast: false
      with:
          python_version: "${{ matrix.python_version }}"
          arch: "${{ matrix.arch }}"